In [2]:
import numpy as np

# 1. Creating NumPy Arrays

Every element in array must have same datatype

In [3]:
arr1 = np.array([1,2,3,4,5]) # 1D
print(arr1)
print()
arr2 = np.array([[1,1,1],[2,2,2],[2,5,3]],) # 2D
print(arr2)

[1 2 3 4 5]

[[1 1 1]
 [2 2 2]
 [2 5 3]]


In [4]:
# Arrays from scratch

print(np.zeros((3,2))) # 3x2 with all 0
print()   
print(np.ones((2,2)))  # 2x2 with all 1
print()    
print(np.full((3,3),5))  # 3x3 with all 5
print()    
print(np.eye(3)) # identity matrix of 3
print()    
print(np.linspace(1,10,5)) # divides 1 to 10 into 5 equal parts
print()
print(np.arange(1,5,1))   # 1 to 5 with gap of 1


[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[[5 5 5]
 [5 5 5]
 [5 5 5]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[ 1.    3.25  5.5   7.75 10.  ]

[1 2 3 4]


# 2.Array Properties

In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape) 
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype) 

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


# 3. Reshaping Array

In [9]:
arr = np.array([[1,2,5],[4,5,8]])
print(arr)
print()
print(arr.shape)
print()
reshaped = arr.reshape(3,2)
print(reshaped)

[[1 2 5]
 [4 5 8]]

(2, 3)

[[1 2]
 [5 4]
 [5 8]]


In [11]:
# Flattening array ( 2D to 1D)

FLAT = arr.flatten()
FLAT

array([1, 2, 5, 4, 5, 8])