# Single Dimension

In [4]:
import numpy as np

arr = np.array([1,2,5,4,6,7,8,9])

print(arr[0]) # single element
print(arr[0:3]) # multiple

1
[1 2 5]


In [9]:
sliced = arr[1:5] # we think its a copy of array but no it is a view(original part)
print(sliced)

sliced[0] = 0 # this will change the original array
arr

[0 5 4 6]


array([1, 0, 5, 4, 6])

# Fancy Indexing & Boolean Masking

In [10]:
# Fancy Indexing (Select Multiple Elements)

arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4] 
print(arr[idx])

[10 30 50]


In [14]:
# Boolean Masking (Filter Data)

arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  
print(arr[mask]) 

[30 40 50]
