# Multi Dimension

# 1. Understanding Axes in NumPy

1D array → 1 axis (axis 0)  
2D array → 2 axes (axis 0 = rows, axis 1 = columns)  
3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)  


In [5]:
import numpy as np

arr1 = np.array([1,2,3])
print(np.sum(arr1))

arr2 = np.array([[1,2,3],[3,2,5]])
print(np.sum(arr2,axis=0))
print(np.sum(arr2,axis=1))
print(np.sum(arr2))

6
[4 4 8]
[ 6 10]
16


# 2. Indexing in Multidimensional Arrays


In [12]:
print(arr2[0,2]) # indexing starts with 0

print(arr2[0:2, 1:2])

3
[[2]
 [2]]


In [17]:
# 3D array

arr3 = np.array([[[1,2,3],[2,1,4]],[[2,1,3],[4,2,5]]] )
arr3.shape

(2, 2, 3)

In [19]:
print(arr3[0, 1, 2]) 
print(arr3[:, 0, :])

4
[[1 2 3]
 [2 1 3]]
